### ISSUE TITLE
[Fabric 1.20.1] Unknown custom ingredient type: valhelsia_core:platform_dependent

### ISSUE THREAD

**Issue by cai-tan** [ValhelsiaTeam/Valhelsia-Furniture#14]
All recipes are unusable. Tried this with a fresh install with literally only Fabric API, JEI, Core, and Furniture.

[Logs](https://mclo.gs/3qPDkuY)
Mods (testing instance):
- Fabric API 0.92.1+1.20.1
- Just Enough Items 15.3.0.4
- Valhelsia Core 1.1.1
- Valhelsia Furniture 1.1.3 (Version number is noticeably missing from Prism Launcher's listing.)

For reference, if I install 1.1.2, the problem is gone.

**Comment by cai-tan** [comment]
I just noticed that one of the most recent changes to this mod was that it was "updated to Valhelsia Core 1.1.3".

*There is no Valhelsia Core 1.1.3.*

I thought that maybe it was just uploaded to Curseforge and not Modrinth, but I checked there, and nope. Curseforge also does not have a Core 1.1.3 version either.

There isn't even a Core 1.1.3 for Forge, either, across ***ALL MINECRAFT VERSIONS.***

**Comment by Vaelzan** [comment]
1.1.2 has been uploaded to CF now. :)
