### ISSUE TITLE
Can't craft wooden slabs

### ISSUE THREAD

**Issue by FeelsbadLemon** [ValhelsiaTeam/Valhelsia-Furniture#17]
I can't craft oak slabs when arranging 3 oak planks in a horizontal line as you do, instead it creates an oak table from valhelsia-furniture.

What gives? Surely this isn't intentional. I think maybe the recipe is bugged.

Playing on 1.20.1 with a moderate amount of mods. Pack put together by myself.

**Comment by Vaelzan** [comment]
It's a bug in KubeJS removing the sticks from our recipes. You can find a fix here for now, until (if) it's fixed in the mod itself: https://github.com/ValhelsiaTeam/Valhelsia-Furniture/issues/10#issuecomment-1865811613

This is also a duplicate issue.
