### ISSUE TITLE
[1.19.2] Spruce Desk causing crash

### ISSUE THREAD

**Issue by AzureDoom** [ValhelsiaTeam/Valhelsia-Furniture#3]
Mod version: valhelsia_furniture-forge-1.19.2-1.0.2
Structures version: valhelsia_structures-forge-1.19.2-1.0.0

Crash report: https://gist.github.com/AzureDoom/7fb7e59170e0ccb12e66dc0fb562f3d0

**Comment by skies912** [comment]
I would like to extend this issue ticket:
This happens with ANY variant of the desk block, including the drawers ones.
When I TPed to the exact block in question, it was the "middle" section between the end and drawer block. Chair was in front of middle section. 

EDIT: Did some specific case testing too. It seems to only crash when using 3-wide desks (thinks like DSK,DSK,DWR or DSK,DWR,DSK) in any configuration with the chair in middle. Exception layout where it doesn't crash seems to be: DWR/DWR/DSK
EDIT: Oh, this only crashes when the world is reloaded; ie teleporting to another region etc. I can fly around normally without issue.

Crash report: [link from NotEnoughCrashes]
https://bytebin.lucko.me/X2DN9RHFz0
